# wifi
WIFI_SSID = "SecuriFi-Hub" # TODO
WIFI_PASSWORD = "stefanecelmaitare--Rebecca06/07" # TODO

MASTER_MAC = "58:E6:C5:12:05:E0" # COM6 # TODO

MQ2_PIN = 0 # TODO
MQ2_THRESHOLD = 1500 # TODO

# traffic generator
TRAFFIC_RATE_PPS = 20

# mvs 
GAIN_LOCK_PACKETS = 100
THRESHOLD_MULT = 2.3 # TODO

# esp now:
ESPNOW_CHANNEL = None # TODO
ESPNOW_MAX_RETRIES = 3
ESPNOW_TX_INTERVAL_MS = 500


# watchdog:
WATCHDOG_SECONDS = 60

SENSOR_POLL_MS = 1000 // TRAFFIC_RATE_PPS

