# wifi:
WIFI_SSID = "SecuriFi-Hub"
WIFI_PASSWORD = "stefanecelmaitare--Rebecca06/07"

# mqtt:
MQTT_BROKER = None # TODO
MQTT_PORT = 1883

MQTT_USERNAME = ""
MQTT_PASSWORD = ""

MQTT_TOPIC = "securifi/master"
MQTT_CLIENT_ID = "securifi_master"
MQTT_PUBLISH_INTERVAL_MS = 500
MQTT_RECONNECT_ATTEMPTS = 3

# esp now:
ESPNOW_CHANNEL = None # TODO
SLAVE_MACS = [
    "58:E6:C5:12:05:E0",
    "58:E6:C5:12:04:E0"
] 

SLAVE_TIMEOUT_MS = 2000

TRAFFIC_RATE_PPS = 20

GAIN_LOCK_PACKETS = 100
THRESHOLD_MULT = 2.3 # TODO

# mq2
# MQ2_PIN = 2 # TODO
# MQ2_THRESHOLD = None # TODO

DETECTION_WINDOW = 10
DETECTION_MIN_HITS = 7
DETECTION_PROBABILITY_THRESHOLD = 0.7

# watchdog
WATCHDOG_SECONDS = 60

SENSOR_POLL_MS = 1000 // TRAFFIC_RATE_PPS